---

- name: old installation
  when:
    - stat_glauth_path is defined
    - stat_glauth_path.stat is defined
    - stat_glauth_path.stat.isdir is defined
    - not stat_glauth_path.stat.isdir
  block:
    - name: stop old service
      become: true
      ansible.builtin.service:
        name: glauth
        state: stopped
        enabled: false
      notify:
        - daemon-reload

    - name: remove installed systemd unit
      become: true
      ansible.builtin.file:
        state: absent
        path: /etc/systemd/system/glauth.service
      when:
        - ansible_service_mgr | lower == "systemd"

    - name: remove installed glauth
      become: true
      ansible.builtin.file:
        state: absent
        path: "{{ stat_glauth_path.stat.path }}"

- name: flush handlers
  ansible.builtin.meta: flush_handlers

...
