---

mariadb_debian_repo: "https://ftp.nluug.nl/db/mariadb/repo"

mariadb_root_password: Y5FZfKXzCeOWGf4kBOiFSp6Il

mariadb_root_password_update: true

mariadb_databases:
  - name: glauth

mariadb_users:
  - name: glauth
    host: "%"
    password: "{{ vault__database.glauth }}"
    encrypted: false
    priv: "glauth.*:ALL"

mariadb_config_mysqld:
  bind-address: 0.0.0.0
  # socket: "{{ mariadb_socket }}"
  skip-external-locking:
  skip-name-resolve: 1
  performance_schema: 1
  expire_logs_days: 2
  max_connections: 20

...
