---

mariadb_root_password: Y5FZfKXzCeOWGf4kBOiFSp6Il

mariadb_root_password_update: true

mariadb_databases:
  - name: glauth

mariadb_users:
  - name: glauth
    host: "%"
    password: iWRb6iVpUlynan4QnUTK2oajL1RJ03LA
    priv: "glauth.*:ALL"
    encrypted: false

mariadb_config_mysqld:
  bind-address: 0.0.0.0
  socket: "{{ mariadb_socket }}"
  skip-external-locking:
  skip-name-resolve: 1
  performance_schema: 1
  expire_logs_days: 2
  max_connections: 20
  # fixes
  # 'You do not have the SUPER privilege and binary logging is enabled
  #  (you *might* want to use the less safe log_bin_trust_function_creators variable)'
  log_bin_trust_function_creators: "1"

...
