---
- name: converge
  hosts: all
  gather_facts: true
  any_errors_fatal: true

  environment:
    # https://github.com/ansible/ansible/issues/77133
    # https://github.com/ansible/ansible/pull/76542
    # LANGUAGE: en_UK.utf8

  pre_tasks:
    - name: environment
      ansible.builtin.debug:
        msg:
          - "os family            : {{ ansible_distribution }} ({{ ansible_os_family }})"
          - "distribution version : {{ ansible_distribution_major_version }}"
          - "ansible version      : {{ ansible_version.full }}"
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

  roles:
    - role: ansible-glauth
