---

- name: snakeoil
  src: bodsch.snakeoil
  version: 1.2.6

- name: syslog-ng
  src: bodsch.syslog_ng
  version: 1.4.0

- name: mariadb
  src: bodsch.mariadb
  version: 2.2.13

- name: snapd
  src: bodsch.snapd
  version: 1.1.2

- name: apparmor
  src: bodsch.apparmor
  version: 1.0.1

...
