---

- name: create glauth configuration directory
  file:
    path: "{{ glauth_config_dir }}"
    state: directory
    owner: root
    group: "{{ glauth_system_group }}"
    mode: 0775

- name: create certificate directory
  file:
    path: "{{ glauth_config_dir }}/certs"
    state: directory
    owner: "{{ glauth_system_user }}"
    group: "{{ glauth_system_group }}"
    mode: 0770

- name: create glauth.conf
  template:
    src: "glauth/glauth.conf.j2"
    dest: "{{ glauth_config_dir }}/glauth.conf"
    force: true
    owner: root
    group: "{{ glauth_system_group }}"
    mode: 0664
  notify:
    - validate config
    - reload glauth

- name: copy sql scripts
  copy:
    src: databases
    dest: "{{ glauth_config_dir }}/"
    group: "{{ glauth_system_group }}"
    mode: 0750

- name: create database backends
  include_tasks: backends/sqlite.yml
  when:
    - glauth_backends.sqlite is defined
    - glauth_backends.sqlite.enabled is defined
    - glauth_backends.sqlite.enabled

- name: restart glauth if needed
  meta: flush_handlers

...
