---

name: push to ansible galaxy

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  # workflow_run:
  #   workflows:
  #     - "CI"
  #   branches:
  #     - main
  #   types:
  #     - completed

jobs:
  galaxy:
    name: galaxy
    runs-on: ubuntu-22.04
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4.2.2
        with:
          path: 'ansible-glauth'

      - name: 'Release on galaxy'
        uses: ansible-actions/ansible-galaxy-action@v1.2.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
