---
name: CI

on:
  workflow_run:
    workflows:
      - "code linter"
    types:
      - completed

defaults:
  run:
    working-directory: 'ansible-glauth'

env:
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'
  GH_USER: bodsch
  GH_TOKEN: ${{ github.token }}

jobs:
  arch:
    name: "${{ matrix.image }} / ansible ${{ matrix.ansible-version }} / python ${{ matrix.python_version }}"
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - archlinux:latest
          - artixlinux:latest
        ansible-version:
          - '9.5'
        python_version:
          - '3.12'
        scenario:
          - default

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v4.2.2
        with:
          path: 'ansible-glauth'
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 🐍 set up python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "${{ matrix.python_version }}"

      - name: Install system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-dateutil

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: force reinstall of community.docker
        run: |
          mkdir -p /home/runner/.ansible/collections
          ansible-galaxy collection install community.docker --force

      - name: test with tox
        run: |
          make \
            test \
            -e TOX_SCENARIO="${{ matrix.scenario }}" \
            -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
            -e DISTRIBUTION="${{ matrix.image }}"
